services:
  - type: web
    name: njl-catalogue
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PARQUET_BLOB_URL
        value: "https://njlprodimages.blob.core.windows.net/protopisfolder/BOM_Enriched_Latest_Transdate.parquet"
      - key: AUTH_BLOB_URL
        value: "https://njlprodimages.blob.core.windows.net/protopisfolder/auth.xlsx"
      - key: REFRESH_INTERVAL_MINUTES
        value: "5"
      - key: REFRESH_SECRET
        sync: false
    healthCheckPath: /api/health
